# CMake generated Testfile for 
# Source directory: /home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials
# Build directory: /home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_acceleration_partials_AccelerationPartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_AccelerationPartials")
set_tests_properties(test_acceleration_partials_AccelerationPartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;10;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
add_test(test_acceleration_partials_SphericalHarmonicPartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_SphericalHarmonicPartials")
set_tests_properties(test_acceleration_partials_SphericalHarmonicPartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;15;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
add_test(test_acceleration_partials_MutualSphericalHarmonicPartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_MutualSphericalHarmonicPartials")
set_tests_properties(test_acceleration_partials_MutualSphericalHarmonicPartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;20;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
add_test(test_acceleration_partials_MassRatePartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_MassRatePartials")
set_tests_properties(test_acceleration_partials_MassRatePartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;25;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
add_test(test_acceleration_partials_PolyhedronPartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_PolyhedronPartials")
set_tests_properties(test_acceleration_partials_PolyhedronPartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;30;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
add_test(test_acceleration_partials_RingPartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_RingPartials")
set_tests_properties(test_acceleration_partials_RingPartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;35;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
add_test(test_acceleration_partials_EihPartials "/home/ralkahal/tudat-bundle/tudat/tests/test_acceleration_partials_EihPartials")
set_tests_properties(test_acceleration_partials_EihPartials PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;40;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/orbit_determination/acceleration_partials/CMakeLists.txt;0;")
