# CMake generated Testfile for 
# Source directory: /home/ralkahal/tudat-bundle/tudat/tests/src/io
# Build directory: /home/ralkahal/tudat-bundle/tudat/tests/src/io
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_io_MapTextFileReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_MapTextFileReader")
set_tests_properties(test_io_MapTextFileReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;11;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_MatrixTextFileReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_MatrixTextFileReader")
set_tests_properties(test_io_MatrixTextFileReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;17;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_StreamFilters "/home/ralkahal/tudat-bundle/tudat/tests/test_io_StreamFilters")
set_tests_properties(test_io_StreamFilters PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;23;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_TwoLineElementsTextFileReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_TwoLineElementsTextFileReader")
set_tests_properties(test_io_TwoLineElementsTextFileReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;29;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_BasicInputOutput "/home/ralkahal/tudat-bundle/tudat/tests/test_io_BasicInputOutput")
set_tests_properties(test_io_BasicInputOutput PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;36;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_ParsedDataVectorUtilities "/home/ralkahal/tudat-bundle/tudat/tests/test_io_ParsedDataVectorUtilities")
set_tests_properties(test_io_ParsedDataVectorUtilities PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;41;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_FieldValue "/home/ralkahal/tudat-bundle/tudat/tests/test_io_FieldValue")
set_tests_properties(test_io_FieldValue PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;46;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_TextParser "/home/ralkahal/tudat-bundle/tudat/tests/test_io_TextParser")
set_tests_properties(test_io_TextParser PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;51;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_MissileDatcomReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_MissileDatcomReader")
set_tests_properties(test_io_MissileDatcomReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;56;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_MissileDatcomData "/home/ralkahal/tudat-bundle/tudat/tests/test_io_MissileDatcomData")
set_tests_properties(test_io_MissileDatcomData PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;61;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_DictionaryInputSystem "/home/ralkahal/tudat-bundle/tudat/tests/test_io_DictionaryInputSystem")
set_tests_properties(test_io_DictionaryInputSystem PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;66;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_Extractor "/home/ralkahal/tudat-bundle/tudat/tests/test_io_Extractor")
set_tests_properties(test_io_Extractor PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;71;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_FixedWidthParser "/home/ralkahal/tudat-bundle/tudat/tests/test_io_FixedWidthParser")
set_tests_properties(test_io_FixedWidthParser PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;76;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_SeparatedParser "/home/ralkahal/tudat-bundle/tudat/tests/test_io_SeparatedParser")
set_tests_properties(test_io_SeparatedParser PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;81;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_LinearFieldTransform "/home/ralkahal/tudat-bundle/tudat/tests/test_io_LinearFieldTransform")
set_tests_properties(test_io_LinearFieldTransform PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;86;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_SolarActivityData "/home/ralkahal/tudat-bundle/tudat/tests/test_io_SolarActivityData")
set_tests_properties(test_io_SolarActivityData PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;91;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_MultiArrayReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_MultiArrayReader")
set_tests_properties(test_io_MultiArrayReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;97;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_MultiArrayWriter "/home/ralkahal/tudat-bundle/tudat/tests/test_io_MultiArrayWriter")
set_tests_properties(test_io_MultiArrayWriter PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;103;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_AerodynamicCoefficientReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_AerodynamicCoefficientReader")
set_tests_properties(test_io_AerodynamicCoefficientReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;109;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_OdfFileReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_OdfFileReader")
set_tests_properties(test_io_OdfFileReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;116;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_ReadTabulatedMediaCorrections "/home/ralkahal/tudat-bundle/tudat/tests/test_io_ReadTabulatedMediaCorrections")
set_tests_properties(test_io_ReadTabulatedMediaCorrections PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;119;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_ReadTabulatedWeatherData "/home/ralkahal/tudat-bundle/tudat/tests/test_io_ReadTabulatedWeatherData")
set_tests_properties(test_io_ReadTabulatedWeatherData PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;122;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
add_test(test_io_TrackingTxtFileReader "/home/ralkahal/tudat-bundle/tudat/tests/test_io_TrackingTxtFileReader")
set_tests_properties(test_io_TrackingTxtFileReader PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;125;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/io/CMakeLists.txt;0;")
