# CMake generated Testfile for 
# Source directory: /home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism
# Build directory: /home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_electromagnetism_LorentzStaticMagneticAccelerationAndForce "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_LorentzStaticMagneticAccelerationAndForce")
set_tests_properties(test_electromagnetism_LorentzStaticMagneticAccelerationAndForce PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;17;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_RadiationSourceModel "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_RadiationSourceModel")
set_tests_properties(test_electromagnetism_RadiationSourceModel PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;23;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_LuminosityModel "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_LuminosityModel")
set_tests_properties(test_electromagnetism_LuminosityModel PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;30;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_SourcePanelRadiosityModel "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_SourcePanelRadiosityModel")
set_tests_properties(test_electromagnetism_SourcePanelRadiosityModel PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;35;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_RadiationPressureTargetModel "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_RadiationPressureTargetModel")
set_tests_properties(test_electromagnetism_RadiationPressureTargetModel PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;41;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_RadiationPressureAcceleration "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_RadiationPressureAcceleration")
set_tests_properties(test_electromagnetism_RadiationPressureAcceleration PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;48;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_ReflectionLaw "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_ReflectionLaw")
set_tests_properties(test_electromagnetism_ReflectionLaw PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;53;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_OccultationModel "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_OccultationModel")
set_tests_properties(test_electromagnetism_OccultationModel PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;59;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_SurfacePropertyDistribution "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_SurfacePropertyDistribution")
set_tests_properties(test_electromagnetism_SurfacePropertyDistribution PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;66;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
add_test(test_electromagnetism_YarkovskyAcceleration "/home/ralkahal/tudat-bundle/tudat/tests/test_electromagnetism_YarkovskyAcceleration")
set_tests_properties(test_electromagnetism_YarkovskyAcceleration PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;74;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/electromagnetism/CMakeLists.txt;0;")
