# CMake generated Testfile for 
# Source directory: /home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics
# Build directory: /home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_aerodynamics_AerodynamicMomentAndAerodynamicForce "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_AerodynamicMomentAndAerodynamicForce")
set_tests_properties(test_aerodynamics_AerodynamicMomentAndAerodynamicForce PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;11;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_AerodynamicsNamespace "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_AerodynamicsNamespace")
set_tests_properties(test_aerodynamics_AerodynamicsNamespace PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;17;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_CoefficientGenerator "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_CoefficientGenerator")
set_tests_properties(test_aerodynamics_CoefficientGenerator PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;23;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_ExponentialAtmosphere "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_ExponentialAtmosphere")
set_tests_properties(test_aerodynamics_ExponentialAtmosphere PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;31;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_CustomConstantTemperatureAtmosphere "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_CustomConstantTemperatureAtmosphere")
set_tests_properties(test_aerodynamics_CustomConstantTemperatureAtmosphere PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;37;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_TabulatedAtmosphere "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_TabulatedAtmosphere")
set_tests_properties(test_aerodynamics_TabulatedAtmosphere PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;43;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_HeatTransfer "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_HeatTransfer")
set_tests_properties(test_aerodynamics_HeatTransfer PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;52;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_ControlSurfaceIncrements "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_ControlSurfaceIncrements")
set_tests_properties(test_aerodynamics_ControlSurfaceIncrements PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;60;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_AerodynamicCoefficientsFromFile "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_AerodynamicCoefficientsFromFile")
set_tests_properties(test_aerodynamics_AerodynamicCoefficientsFromFile PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;65;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_WindModel "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_WindModel")
set_tests_properties(test_aerodynamics_WindModel PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;70;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
add_test(test_aerodynamics_MarsDtmAtmosphere "/home/ralkahal/tudat-bundle/tudat/tests/test_aerodynamics_MarsDtmAtmosphere")
set_tests_properties(test_aerodynamics_MarsDtmAtmosphere PROPERTIES  _BACKTRACE_TRIPLES "/home/ralkahal/tudat-bundle/tudat/cmake_modules/yolo/YOLOProjectAddTestCase.cmake;104;add_test;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;75;TUDAT_ADD_TEST_CASE;/home/ralkahal/tudat-bundle/tudat/tests/src/astro/aerodynamics/CMakeLists.txt;0;")
